# Задание 1
Датасет для домашнего задания вы найдете в разделе “Материалы к домашнему заданию” к этому занятию.
Определите, какому фильму было выставлено больше всего оценок 5.0

In [5]:
import pandas as pd
df_1 = pd.read_csv ('movies.csv')
df_1.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [17]:
df_2 = pd.read_csv ('ratings.csv')
# df_2.head()

In [23]:
top_movie = df_2[df_2['rating'] == 5.0]['movieId'].value_counts().idxmax()
top_title = df_1[df_1['movieId'] == top_movie]['title'].item()
number_of_5s = df_2[df_2['rating'] == 5.0]['movieId'].value_counts()

print (top_title)
print (number_of_5s)

Shawshank Redemption, The (1994)
movieId
318       153
296       123
356       116
2571      109
260       104
         ...
668         1
581         1
496         1
347         1
156371      1
Name: count, Length: 2954, dtype: int64

In [14]:
joined = df_2.merge(df_1, on='movieId', how='left')
joined.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [25]:
check_top_movie = joined[joined['rating'] == 5.0]['title'].value_counts().idxmax()
print (check_top_movie)

counts = joined[joined['rating'] == 5.0]['title'].value_counts()
print(f"Фильм: {counts.index[0]}, Кол-во пятерок: {counts.values[0]}")

Shawshank Redemption, The (1994)
Фильм: Shawshank Redemption, The (1994), Кол-во пятерок: 153

# Задание 2
По данным файла power.csv (находится в “Материалы к домашнему заданию”) посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. Не учитывайте в расчётах отрицательные значения quantity

In [43]:
data = pd.read_csv('power.csv')
data.head ()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [46]:
f_countries = data[
    ((data['country'] == 'Lithuania') | (data['country'] == 'Latvia') | (data['country'] == 'Estonia')) 
    & ((data['year'] >= 2005 ) & (data ['year'] <= 2010)) 
    & (data ['quantity']>= 0)    
    & ((data ['category'] == 4) | (data ['category'] == 12) | (data ['category'] == 21))
    ]
f_countries.head()

         country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4

In [47]:
sum_qty_f_countries = f_countries ['quantity']. sum()
print (sum_qty_f_countries)

240580.0